### ISSUE TITLE
I have finished the codes of the easy part, the else is  difficult for me

### ISSUE THREAD

**Issue by dsp6414** [ahmed15reda/Plus-300-Linq-Questions-Northwind#1]
what is the answer for these question?

**Comment by ahmed15reda** [comment]
sorry for the late reply, I have already updated the repo and there are 75 questions have been answered in the easy section and the other will be answered soon

**Comment by ahmed15reda** [comment]
> what is the answer for these question?
sorry for the late reply, I have already updated the repo and there are 75 questions have been answered in the easy section and the other will be answered soon
